config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Units', 'action' => 'upload', 'home']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Entity/Rune.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Rune Entity
 *
 * @property int $id
 * @property int $slot_number
 * @property int $stars
 * @property int $rune_set_id
 * @property int $unit_id
 *
 * @property \App\Model\Entity\RuneSet $rune_set
 * @property \App\Model\Entity\Unit $unit
 * @property \App\Model\Entity\RuneAttribute[] $rune_attributes
 */
class Rune extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true
    ];
}

src/Model/Table/UnitsTable.php
<?php

namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Units Model
 *
 */
class UnitsTable extends Table {

  var $config = [
    'mappings' => [
      'id' => 'unit_id',
      'element_id' => 'attribute',
      'unit_level' => 'unit_level',
      'hp' => '',
      'atk' => 'atk',
      'def' => 'def',
      'spd' => 'spd',
      'cri_rate' => 'critical_rate',
      'cri_damage' => 'critical_damage',
      'resistance' => 'resist',
      'accuracy' => 'accuracy',
      'create_time' => 'create_time',
      'awaken' => '',
      'units_list_id' => '',
      'stars' => 'class'
    ]
  ];

  /**
   * Initialize method
   *
   * @param array $config The configuration for the Table.
   * @return void
   */
  public function initialize(array $config) {
    parent::initialize($config);

    $this->setTable('units');
    $this->setDisplayField('id');
    $this->setPrimaryKey('id');

    $this->belongsTo('Elements', [
      'foreignKey' => 'element_id',
      'joinType' => 'INNER'
    ]);
    $this->belongsTo('UnitsList', [
      'foreignKey' => ['units_list_id', 'awaken', 'element_id'],
      'joinType' => 'INNER'
    ]);
    $this->hasMany('Runes', [
      'foreignKey' => 'unit_id'
    ]);
    $this->addBehavior('UploadFiles');
  }

  /**
   * Default validation rules.
   *
   * @param \Cake\Validation\Validator $validator Validator instance.
   * @return \Cake\Validation\Validator
   */
  public function validationDefault(Validator $validator) {
    $validator
      ->requirePresence('id', 'create');

    $validator
      ->integer('hp')
      ->allowEmpty('hp');

    $validator
      ->integer('atk')
      ->allowEmpty('atk');

    $validator
      ->integer('def')
      ->allowEmpty('def');

    $validator
      ->integer('spd')
      ->allowEmpty('spd');

    $validator
      ->integer('cri_rate')
      ->allowEmpty('cri_rate');

    $validator
      ->integer('cri_damage')
      ->allowEmpty('cri_damage');

    $validator
      ->integer('resistance')
      ->allowEmpty('resistance');

    $validator
      ->integer('accuracy')
      ->allowEmpty('accuracy');

    $validator
      ->boolean('awaken')
      ->allowEmpty('awaken');

    $validator
      ->dateTime('create_time')
      ->allowEmpty('create_time');

    return $validator;
  }

  /**
   * Returns a rules checker object that will be used for validating
   * application integrity.
   *
   * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
   * @return \Cake\ORM\RulesChecker
   */
  public function buildRules(RulesChecker $rules) {
    //$rules->add($rules->existsIn(['element_id'], 'Elements'));
    //$rules->add($rules->existsIn(['units_list_id'], 'UnitsList'));
    //$rules->add($rules->existsIn(['user_id'], 'Users'));

    return $rules;
  }

  public function createUnitsFromFile($file) {
    $filename = $this->uploadFile($file);
    $json = file_get_contents($filename);
    $data = json_decode($json, TRUE);
    $this->bulkCreateUnits($data);
    $this->Runes->createFromFile($data);
  }

  public function bulkCreateUnits($data) {
    if (!is_array($data['unit_list'])) {
      return;
    }
    foreach ($data['unit_list'] as $unit) {
      $parsedUnit = $this->getUnitValues($unit);
      $exisitngUnit = $this->find('all', ['conditions' => ['id' => $unit['unit_id']]])->first();
      if ($exisitngUnit) {
        $unitEntity = $this->patchEntity($exisitngUnit, $parsedUnit);
      }
      else {
        $unitEntity = $this->newEntity($parsedUnit);
      }
      if ($this->save($unitEntity) && !empty($unit['runes'])) {
        $this->Runes->createFromUnit($unit['runes'], $unitEntity->id);
      }
    }
  }

  public function getUnitValues($unit) {
    $parsedUnit = [];
    foreach ($this->config['mappings'] as $target => $source) {
      if ($source && $unit[$source]) {
        $parsedUnit[$target] = $unit[$source];
      }
    }
    $parsedUnit['hp'] = $unit['con'] * 15;
    $parsedUnit['units_list_id'] = (int) substr($unit['unit_master_id'], 0, 3);
    $parsedUnit['awaken'] = !!substr($unit['unit_master_id'], -2, 1);
//    $parsedUnit['create_time'] = strtotime($unit['create_time']);
    return $parsedUnit;
  }

  public function beforeFind($event, $query, $options, $primary) {
    $query->order(['stars' => 'DESC', 'unit_level' => 'DESC', 'Units.element_id' => 'ASC']);
  }

}

src/Controller/RunesController.php
<?php

namespace App\Controller;

use App\Controller\AppController;
use Cake\Utility\Hash;

/**
 * Runes Controller
 *
 * @property \App\Model\Table\RunesTable $Runes
 */
class RunesController extends AppController {

  public function initialize() {
    parent::initialize();
    $this->loadComponent('RequestHandler');
  }

  /**
   * Index method
   *
   * @return \Cake\Network\Response|null
   */
  public function index() {
    if ($this->request->is('ajax') || $_GET['ajax']) {
      $this->viewBuilder()->setLayout('ajax');
      $options = [
        'contain' => ['RuneAttributes', 'RuneSets'],
        'order' => ['Runes.rune_set_id' => 'DESC', 'Runes.slot_number' => 'ASC'],
        'search_data' => $this->request->getQuery(),
      ];
      $runesArray = $this->Runes->find('searchQuery', $options);
      if (isset($runesArray['errors'])) {
        $this->response->statusCode(412);
        $runes = $runesArray;
      }
      else {
        $runes = Hash::combine($runesArray, '{n}.id', '{n}');
      }
    }
    else {
      $this->paginate = [
        'contain' => ['RuneSets', 'RuneAttributes', 'Units', 'Units.UnitsList'],
        'conditions' => ['Runes.stars > ' => 0],
        'order' => ['unit_id' => 'DESC', 'Runes.slot_number' => 'ASC'],
      ];
      $runes = $this->paginate($this->Runes);
    }
    $this->set(compact('runes'));
    $this->set('_serialize', ['runes']);
  }

  /**
   * View method
   *
   * @param string|null $id Rune id.
   * @return \Cake\Network\Response|null
   * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
   */
  public function view($id = null) {
    $rune = $this->Runes->get($id, [
      'contain' => ['RuneSets', 'RuneAttributes', 'Units']
    ]);
    $this->set('rune', $rune);
    $this->set('_serialize', ['rune']);
  }

  /**
   * Add method
   *
   * @return \Cake\Network\Response|null Redirects on successful add, renders view otherwise.
   */
  public function add() {
    $rune = $this->Runes->newEntity();
    if ($this->request->is('post')) {
      $rune = $this->Runes->patchEntity($rune, $this->request->getData());
      if ($this->Runes->save($rune)) {
        $this->Flash->success(__('The rune has been saved.'));

        return $this->redirect(['action' => 'index']);
      }
      $this->Flash->error(__('The rune could not be saved. Please, try again.'));
    }
    $runeSets = $this->Runes->RuneSets->find('list', ['limit' => 200]);
    $units = $this->Runes->Units->find('list', ['limit' => 200]);
    $this->set(compact('rune', 'runeSets', 'units'));
    $this->set('_serialize', ['rune']);
  }

  /**
   * Edit method
   *
   * @param string|null $id Rune id.
   * @return \Cake\Network\Response|null Redirects on successful edit, renders view otherwise.
   * @throws \Cake\Network\Exception\NotFoundException When record not found.
   */
  public function edit($id = null) {
    $rune = $this->Runes->get($id, [
      'contain' => []
    ]);
    if ($this->request->is(['patch', 'post', 'put'])) {
      $rune = $this->Runes->patchEntity($rune, $this->request->getData());
      if ($this->Runes->save($rune)) {
        $this->Flash->success(__('The rune has been saved.'));
        return $this->redirect(['action' => 'index']);
      }
      $this->Flash->error(__('The rune could not be saved. Please, try again.'));
    }
    $runeSets = $this->Runes->RuneSets->find('list', ['limit' => 200]);
    $units = $this->Runes->Units->find('list', ['limit' => 200]);
    $this->set(compact('rune', 'runeSets', 'units'));
    $this->set('_serialize', ['rune']);
  }

  /**
   * Delete method
   *
   * @param string|null $id Rune id.
   * @return \Cake\Network\Response|null Redirects to index.
   * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
   */
  public function delete($id = null) {
    $this->request->allowMethod(['post', 'delete']);
    $rune = $this->Runes->get($id);
    if ($this->Runes->delete($rune)) {
      $this->Flash->success(__('The rune has been deleted.'));
    }
    else {
      $this->Flash->error(__('The rune could not be deleted. Please, try again.'));
    }
    return $this->redirect(['action' => 'index']);
  }

  public function searchForm() {
    
  }

}

src/Template/Runes/index.ctp
<?php
/**
 * @var \App\View\AppView $this
 */
?>
<nav class="col-lg-2 col-sm-4 hidden-xs" id="actions-sidebar">
    <ul class="navbar navbar-left">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Html->link(__('List Units'), ['controller' => 'Units', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('Upload Units'), ['controller' => 'Units', 'action' => 'upload']) ?></li>
    </ul>
</nav>
<div class="runes index col-lg-10 col-sm-8 col-xs-12 table-responsive">
    <h3><?= __('Runes') ?></h3>
    <table class="table table-hover table-responsive" cellpadding="0" cellspacing="0">
        <thead class="table-inverse">
            <tr>
                <th scope="col"><?= $this->Paginator->sort('slot_number') ?></th>
                <th scope="col"><?= $this->Paginator->sort('stars') ?></th>
                <th scope="col"><?= $this->Paginator->sort('level') ?></th>
                <th scope="col"><?= $this->Paginator->sort('rune_set_id') ?></th>
                <th scope="col"><?= $this->Paginator->sort('unit_id') ?></th>
                <th scope="col" class="actions"><?= __('Actions') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($runes as $rune): ?>
              <tr class="<?= $rune->slot_number ?> <?= $rune->rune_set->description ?>">
                  <td><?= $this->Number->format($rune->slot_number) ?></td>
                  <td><?= $this->Number->format($rune->stars) ?></td>
                  <td><?= $this->Number->format($rune->upgrade_curr) ?></td>
                  <td><?= $rune->rune_set->description ?></td>
                  <td><?= $rune->has('unit') ? $this->Html->link($rune->unit->units_list->description, ['controller' => 'Units', 'action' => 'view', $rune->unit->id]) : 'no unit' ?></td>
                  <td class="actions">
                      <?= $this->Html->link(__('View'), ['action' => 'view', $rune->id]) ?>
                  </td>
              </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <div class="paginator">
        <ul class="pagination">
            <?= $this->Paginator->first('<< ' . __('first')) ?>
            <?= $this->Paginator->prev('< ' . __('previous')) ?>
            <?= $this->Paginator->numbers() ?>
            <?= $this->Paginator->next(__('next') . ' >') ?>
            <?= $this->Paginator->last(__('last') . ' >>') ?>
        </ul>
        <p><?= $this->Paginator->counter(['format' => __('Page {{page}} of {{pages}}, showing {{current}} record(s) out of {{count}} total')]) ?></p>
    </div>
</div>

src/Template/Runes/view.ctp
<nav class="col-lg-2 col-sm-4 hidden-xs" id="actions-sidebar">
    <ul class="navbar navbar-left">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Html->link(__('List Units'), ['controller' => 'Units', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('Upload Units'), ['controller' => 'Units', 'action' => 'upload']) ?></li>
    </ul>
</nav>
<div class="unitsList index col-lg-10 col-sm-8 col-xs-12 table-responsive">

</div>